### ISSUE TITLE
promql instant query generates `float` type error with null data overwrite

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/rw-public-codecollection#22]
## Expected Behavior
PromQL SLI to capture and push the proper value from the query `sum(up offset 1m)` as the SLI. 

## Current Behavior
SLI codebundle provides the following result and error error: 

```
Arguments: [ data={'result': [{'metric': {}, 'value': [1672242515.217, '4']}],
 'resultType': 'vector'} | method='Last' | no_result_overwrite=False | no_result_value=0.0 ]
TypeError: 'float' object is not subscriptable
Traceback (most recent call last):
  File "/collection/libraries/RW/Prometheus/Prometheus.py", line 250, in transform_data
    column = [float(row[column_index]) for row in metric_data]
  File "/collection/libraries/RW/Prometheus/Prometheus.py", line 250, in <listcomp>
    column = [float(row[column_index]) for row in metric_data]
TypeError: 'float' object is not subscriptable
```

## Possible Solution
Change and test how the null data value is being handled.

**Comment by jon-funk** [comment]
Have you tried with the `Raw` transform option? Looking at the code and the result here it appears you're getting a single aggregated result that should always be present (so I don't think we need the result overwrite which looks like it's off so that's good)

A gotcha with the prom rest response is certain functions will change the result key from `results` (timeseries) to `result` (data point) and in that case `Raw` should work, whereas `Last` assumes a timeseries - let me know if that works for you. Now that we have the readmes I should include a rundown of the responses there and when to use the transforms.

**Comment by stewartshea** [comment]
Raw is actually excluded from the available types, though I plan on adding
it back in.

--
Shea Stewart (he/him)
c:647-972-5191 ***@***.***
Book a meeting https://calendly.com/stewartshea

**Comment by jon-funk** [comment]
Wrote the functionality but didn't expose it in the form :face_with_spiral_eyes: egg on my face.

**Comment by stewartshea** [comment]
No worries. I saw it in there and will fix it up this weekend, I've already
started to work on it but won't be back at the desk until tomorrow. I have
other use cases to test out as well so I'd love to make sure I'm well
covered before sending in the full PR.

--
Shea Stewart (he/him)
c:647-972-5191 ***@***.***
Book a meeting https://calendly.com/stewartshea

**Comment by stewartshea** [comment]
I exposed the option and the `Raw` type worked well for my use case. Will close now and we can open another issue if this occurs in other instances where `Raw` isn't the desired option.
